## Image Dataset Test Notebook

The goal of this notebook is to check that the dataset created by **Img_dataset.py** is correct.<br>
In particular, the labels saved by the simulator should match the true road lanes.

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import matplotlib.pyplot as plt
import torch


from data.ImageDataset import ImageDataset,convert_tensor_to_numpy
from utils.visualization import display_input
 

from serde import Experiment


In [6]:
# Creating an experiment to check the performance of the Simulator and the Img_dataset class.
exp = Experiment(name='TestExp', new=True, overwrite=True)

In [7]:
# Creating the dataset with the desired parameters (a small batch size is enough).
inspect_dataset =  ImageDataset( dataset_name='InspectSet', size=3, cfg_path=exp.params['cfg_path'])


inspect_loader = torch.utils.data.DataLoader(dataset=inspect_dataset,
                                              batch_size=1,
                                              shuffle=True, num_workers=1)

In [8]:
# Iterating the dataset and displaying the image and the labels. 
# Check visually that the labels correspond to the true road lanes.
# Note the order of the images is different each time you run this cell.
# This is because the shuffle argument in the inspector_loader (defined in the previous cell)
# is set to True.

for i, (images, labels) in enumerate( inspect_loader ):
    
    # Select first image from minibatch
    image = images[0]
    label = labels[0]
    
    # Convert to numpy
    image = convert_tensor_to_numpy(image)
    label = convert_tensor_to_numpy(label)
    
    # Plot the arrays
    display_input(image,label)



IndexError: Traceback (most recent call last):
  File "/home/mlisp-1/anaconda2/envs/lab/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "data/ImageDataset.py", line 334, in __getitem__
    label = get_label_array(self.dataset_path, self.detections_file_name, image_name)
  File "data/ImageDataset.py", line 87, in get_label_array
    label[coords] = 1
IndexError: too many indices for array


In [6]:
%debug

ERROR:root:No traceback has been produced, nothing to debug.


In [7]:
import numpy as np
import torch

a = np.ones((2,2,3))
# Setting diffent values for each channel
a[:,:,0] = 10 
a[:,:,1] = 100
a[:,:,2] = 200

print(a)

[[[ 10. 100. 200.]
  [ 10. 100. 200.]]

 [[ 10. 100. 200.]
  [ 10. 100. 200.]]]


In [8]:
b = np.transpose(a, axes=(2,1,0))
print(b.shape)

(3, 2, 2)


In [9]:
c = np.transpose(b, axes=(2,1,0))
print(c.shape)

(2, 2, 3)


In [10]:
print(c)

[[[ 10. 100. 200.]
  [ 10. 100. 200.]]

 [[ 10. 100. 200.]
  [ 10. 100. 200.]]]


## Create Training Data Sets

In [11]:

inspect_dataset =  ImageDataset( dataset_name='Image_set_unaugmented_s1', size=250, seed=1, cfg_path=exp.params['cfg_path'])
inspect_dataset =  ImageDataset( dataset_name='Image_set_unaugmented_s2', size=250, seed=2, cfg_path=exp.params['cfg_path'])
inspect_dataset =  ImageDataset( dataset_name='Image_set_unaugmented_s3', size=250, seed=3, cfg_path=exp.params['cfg_path'])
inspect_dataset =  ImageDataset( dataset_name='Image_set_unaugmented_s4', size=250, seed=4, cfg_path=exp.params['cfg_path'])

test_dataset = ImageDataset( dataset_name='Image_set_test_s5', size=100, seed=5, cfg_path=exp.params['cfg_path'])